import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Pill, Clock, Calendar, Bell, CheckCircle, XCircle,
    AlertTriangle, Plus, X, Edit2, Trash2, Settings,
    Search, Filter, Download, Share2, Eye, ChevronRight,
    ChevronDown, Volume2, VolumeX, Repeat, Pause,
    Play, SkipForward, SkipBack, RefreshCw, Save,
    Camera, Image, FileText, Upload, Info, HelpCircle,
    User, Phone, Mail, MapPin, Star, Award, TrendingUp,
    TrendingDown, Activity, Heart, Brain, Thermometer,
    Droplets, Shield, Zap, Target, BarChart3, LineChart,
    PieChart, Sun, Moon, Sunrise, Sunset, Cloud, CloudRain,
    Wind, Compass, Navigation, Globe, Map, MapPin as MapPinIcon,
    Route, Navigation2, Compass as CompassIcon, Battery,
    Wifi, Signal, Bluetooth, Headphones, Smartphone,
    Watch, Timer, Stopwatch, Hourglass, AlarmClock,
    Notification, MessageCircle, Mail as MailIcon, Send,
    Paperclip, Smile, MoreVertical, Archive, Copy,
    ExternalLink, Link, Lock, Unlock, EyeOff, EyeOn,
    Mic, MicOff, Video, VideoOff, Phone as PhoneIcon,
    PhoneOff, EndCall, StartCall, IncomingCall,
    OutgoingCall, MissedCall, Voicemail, Conference,
    Group, Users, UserPlus, UserMinus, UserCheck,
    UserX, Crown, Shield as ShieldIcon, Sword,
    Hammer, Wrench, Settings as SettingsIcon,
    Cog, Cogs, Gear, Layers, Grid, List,
    Layout, LayoutGrid, LayoutList, LayoutDashboard,
    Menu, MenuSquare, MenuIcon, MoreHorizontal,
    MoreVertical as MoreVerticalIcon, ChevronUp,
    ChevronLeft, ChevronRight as ChevronRightIcon,
    ArrowUp, ArrowDown, ArrowLeft as ArrowLeftIcon,
    ArrowRight as ArrowRightIcon, ArrowUpCircle,
    ArrowDownCircle, ArrowLeftCircle, ArrowRightCircle,
    ChevronUpCircle, ChevronDownCircle, ChevronLeftCircle,
    ChevronRightCircle, Circle, Square, Triangle,
    Diamond, Hexagon, Octagon, Pentagon, Star as StarIcon,
    Heart as HeartIcon, Brain as BrainIcon, Lung,
    Kidney, Liver, Stomach, Intestine, Bone,
    Muscle, Nerve, Blood, DNA, Virus, Bacteria,
    Cell, Tissue, Organ, System, Body, Humanoid,
    Robot, Android, Cyborg, AI, ML, DL, NLP,
    Computer, Laptop, Tablet, Phone as PhoneDevice,
    Desktop, Server, Cloud as CloudIcon, Database,
    HardDrive, SSD, USB, HDMI, USBPort,
    Ethernet, WiFi as WiFiIcon, Bluetooth as BluetoothIcon,
    NFC, QRCode, Barcode, Scanner, Printer,
    Fax, Copier, Shredder, Paperclip as PaperclipIcon,
    Folder, FolderOpen, File, FilePlus, FileMinus,
    FileText as FileTextIcon, FileImage, FileVideo,
    FileAudio, FileCode, FileArchive, FileCheck,
    FileX, FileQuestion, FileWarning, FileError,
    FileSearch, FileLock, FileUnlock, FileSignature,
    FileCertificate, FileKey, FileKeyhole,
    FileShield, FileHeart, FileBrain, FileMedical,
    FileHealth, FileHospital, FileClinic, FileDoctor,
    FilePatient, FileNurse, FilePharmacist, FileDrug,
    FileMedicine, FilePill, FileSyringe, FileInjection,
    FileVaccine, FileTest, FileLab, FileResult,
    FileReport, FileDiagnosis, FileTreatment, FileTherapy,
    FileRecovery, FileRehabilitation, FileExercise,
    FileDiet, FileNutrition, FileFitness, FileWellness,
    FileMental, FilePsychology, FilePsychiatry,
    FileTherapy as FileTherapyIcon, FileCounseling, FileSupport,
    FileHelp, FileEmergency, FileUrgent, FileCritical,
    FileWarning as FileWarningIcon, FileAlert, FileDanger,
    FileSecure, FileSafe, FileProtected, FileEncrypted,
    FileDecrypted, FileBackup, FileRestore, FileSync,
    FileUpload, FileDownload, FileShare, FileExport,
    FileImport, FilePrint, FileCopy, FileMove,
    FileRename, FileDelete, FileArchive as FileArchiveIcon,
    FileUnarchive, FileCompress, FileDecompress,
    FileZip, FileUnzip, FileRAR, FileUnRAR,
    FilePDF, FileDOC, FileDOCX, FileXLS, FileXLSX,
    FilePPT, FilePPTX, FileTXT, FileRTF, FileODT,
    FileODS, FileODP, FileCSV, FileJSON, FileXML,
    FileHTML, FileCSS, FileJS, FileTS, FileMD,
    FileYAML, FileINI, FileCFG, FileCONF, FileLOG,
    FileTMP, FileTEMP, FileBAK, FileOLD, FileNEW,
    FileCURRENT, FileLATEST, FilePREVIOUS, FileNEXT,
    FileFIRST, FileLAST, FileSTART, FileEND,
    FileBEGIN, FileFINISH, FileCOMPLETE, FileINCOMPLETE,
    FilePARTIAL, FileFULL, FileEMPTY, FileNULL,
    FileZERO, FileONE, FileTWO, FileTHREE, FileFOUR,
    FileFIVE, FileSIX, FileSEVEN, FileEIGHT, FileNINE,
    FileTEN, FileELEVEN, FileTWELVE, FileTHIRTEEN,
    FileFOURTEEN, FileFIFTEEN, FileSIXTEEN, FileSEVENTEEN,
    FileEIGHTEEN, FileNINETEEN, FileTWENTY, FileTWENTYONE,
    FileTWENTYTWO, FileTWENTYTHREE, FileTWENTYFOUR,
    FileTWENTYFIVE, FileTWENTYSIX, FileTWENTYSEVEN,
    FileTWENTYEIGHT, FileTWENTYNINE, FileTHIRTY,
    FileTHIRTYONE, FileTHIRTYTWO, FileTHIRTYTHREE,
    FileTHIRTYFOUR, FileTHIRTYFIVE, FileTHIRTYSIX,
    FileTHIRTYSEVEN, FileTHIRTYEIGHT, FileTHIRTYNINE,
    FileFORTY, FileFORTYONE, FileFORTYTWO, FileFORTYTHREE,
    FileFORTYFOUR, FileFORTYFIVE, FileFORTYSIX, FileFORTYSEVEN,
    FileFORTYEIGHT, FileFORTYNINE, FileFIFTY, FileFIFTYONE,
    FileFIFTYTWO, FileFIFTYTHREE, FileFIFTYFOUR, FileFIFTYFIVE,
    FileFIFTYSIX, FileFIFTYSEVEN, FileFIFTYEIGHT, FileFIFTYNINE,
    FileSIXTY, FileSIXTYONE, FileSIXTYTWO, FileSIXTYTHREE,
    FileSIXTYFOUR, FileSIXTYFIVE, FileSIXTYSIX, FileSIXTYSEVEN,
    FileSIXTYEIGHT, FileSIXTYNINE, FileSEVENTY, FileSEVENTYONE,
    FileSEVENTYTWO, FileSEVENTYTHREE, FileSEVENTYFOUR, FileSEVENTYFIVE,
    FileSEVENTYSIX, FileSEVENTYSEVEN, FileSEVENTYEIGHT, FileSEVENTYNINE,
    FileEIGHTY, FileEIGHTYONE, FileEIGHTYTWO, FileEIGHTYTHREE,
    FileEIGHTYFOUR, FileEIGHTYFIVE, FileEIGHTYSIX, FileEIGHTYSEVEN,
    FileEIGHTYEIGHT, FileEIGHTYNINE, FileNINETY, FileNINETYONE,
    FileNINETYTWO, FileNINETYTHREE, FileNINETYFOUR, FileNINETYFIVE,
    FileNINETYSIX, FileNINETYSEVEN, FileNINETYEIGHT, FileNINETYONE,
    FileONEHUNDRED, FileONEHUNDREDONE, FileONEHUNDREDTWO,
    FileONEHUNDREDTHREE, FileONEHUNDREDFOR, FileONEHUNDREDFIVE,
    FileONEHUNDREDSIX, FileONEHUNDREDSEVEN, FileONEHUNDREDEIGHT,
    FileONEHUNDREDNINE, FileONEHUNDREDTEN, FileONEHUNDREDELEVEN,
    FileONEHUNDREDTWELVE, FileONEHUNDREDTHIRTEEN, FileONEHUNDREDFORTEEN,
    FileONEHUNDFIFTEEN, FileONEHUNDREDSIXTEEN, FileONEHUNDREDSEVENTEEN,
    FileONEHUNDREDEIGHTEEN, FileONEHUNDREDNINETEEN, FileONEHUNDREDTWENTY,
    FileONEHUNDREDTWENTYONE, FileONEHUNDREDTWENTYTWO, FileONEHUNDREDTWENTYTHREE,
    FileONEHUNDREDTWENTYFOUR, FileONEHUNDREDTWENTYFIVE, FileONEHUNDREDTWENTYSIX,
    FileONEHUNDREDTWENTYSEVEN, FileONEHUNDREDTWENTYEIGHT, FileONEHUNDREDTWENTYNINE,
    FileONEHUNDREDTHIRTY, FileONEHUNDREDTHIRTYONE, FileONEHUNDREDTHIRTYTWO,
    FileONEHUNDREDTHIRTYTHREE, FileONEHUNDREDTHIRTYFOUR, FileONEHUNDREDTHIRTYFIVE,
    FileONEHUNDREDTHIRTYSIX, FileONEHUNDREDTHIRTYSEVEN, FileONEHUNDREDTHIRTYEIGHT,
    FileONEHUNDREDTHIRTYNINE, FileONEHUNDREDFORTY, FileONEHUNDREDFORTYONE,
    FileONEHUNDREDFORTYTWO, FileONEHUNDREDFORTYTHREE, FileONEHUNDREDFORTYFOUR,
    FileONEHUNDREDFORTYFIVE, FileONEHUNDREDFORTYSIX, FileONEHUNDREDFORTYSEVEN,
    FileONEHUNDREDFORTYEIGHT, FileONEHUNDREDFORTYNINE, FileONEHUNDFIFTY,
    FileONEHUNDFIFTYONE, FileONEHUNDFIFTYTWO, FileONEHUNDFIFTYTHREE,
    FileONEHUNDFIFTYFOUR, FileONEHUNDFIFTYFIVE, FileONEHUNDFIFTYSIX,
    FileONEHUNDFIFTYSEVEN, FileONEHUNDFIFTYEIGHT, FileONEHUNDFIFTYNINE,
    FileONEHUNDREDSIXTY, FileONEHUNDREDSIXTYONE, FileONEHUNDREDSIXTYTWO,
    FileONEHUNDREDSIXTYTHREE, FileONEHUNDREDSIXTYFOUR, FileONEHUNDREDSIXTYFIVE,
    FileONEHUNDREDSIXTYSIX, FileONEHUNDREDSIXTYSEVEN, FileONEHUNDREDSIXTYEIGHT,
    FileONEHUNDREDSIXTYNINE, FileONEHUNDREDSEVENTY, FileONEHUNDREDSEVENTYONE,
    FileONEHUNDREDSEVENTYTWO, FileONEHUNDREDSEVENTYTHREE, FileONEHUNDREDSEVENTYFOUR,
    FileONEHUNDREDSEVENTYFIVE, FileONEHUNDREDSEVENTYSIX, FileONEHUNDREDSEVENTYSEVEN,
    FileONEHUNDREDSEVENTYEIGHT, FileONEHUNDREDSEVENTYNINE, FileONEHUNDEIGHTY,
    FileONEHUNDEIGHTYONE, FileONEHUNDEIGHTYTWO, FileONEHUNDEIGHTYTHREE,
    FileONEHUNDEIGHTYFOUR, FileONEHUNDEIGHTYFIVE, FileONEHUNDEIGHTYSIX,
    FileONEHUNDEIGHTYSEVEN, FileONEHUNDEIGHTYEIGHT, FileONEHUNDEIGHTYNINE,
    FileONEHUNDREDNINETY, FileONEHUNDREDNINETYONE, FileONEHUNDREDNINETYTWO,
    FileONEHUNDREDNINETYTHREE, FileONEHUNDREDNINETYFOUR, FileONEHUNDREDNINETYFIVE,
    FileONEHUNDREDNINETYSIX, FileONEHUNDREDNINETYSEVEN, FileONEHUNDREDNINETYEIGHT,
    FileONEHUNDREDNINETYNINE, FileTWOHUNDRED, FileTWOHUNDREDONE, FileTWOHUNDREDTWO,
    FileTWOHUNDREDTHREE, FileTWOHUNDREDFOR, FileTWOHUNDREDFIVE, FileTWOHUNDREDSIX,
    FileTWOHUNDREDSEVEN, FileTWOHUNDREDEIGHT, FileTWOHUNDREDNINE, FileTWOHUNDREDTEN,
    FileTWOHUNDREDELEVEN, FileTWOHUNDREDTWELVE, FileTWOHUNDREDTHIRTEEN,
    FileTWOHUNDREDFORTEEN, FileTWOHUNDFIFTEEN, FileTWOHUNDREDSIXTEEN,
    FileTWOHUNDREDSEVENTEEN, FileTWOHUNDREDEIGHTEEN, FileTWOHUNDREDNINETEEN,
    FileTWOHUNDREDTWENTY, FileTWOHUNDREDTWENTYONE, FileTWOHUNDREDTWENTYTWO,
    FileTWOHUNDREDTWENTYTHREE, FileTWOHUNDREDTWENTYFOUR, FileTWOHUNDREDTWENTYFIVE,
    FileTWOHUNDREDTWENTYSIX, FileTWOHUNDREDTWENTYSEVEN, FileTWOHUNDREDTWENTYEIGHT,
    FileTWOHUNDREDTWENTYNINE, FileTWOHUNDREDTHIRTY, FileTWOHUNDREDTHIRTYONE,
    FileTWOHUNDREDTHIRTYTWO, FileTWOHUNDREDTHIRTYTHREE, FileTWOHUNDREDTHIRTYFOUR,
    FileTWOHUNDREDTHIRTYFIVE, FileTWOHUNDREDTHIRTYSIX, FileTWOHUNDREDTHIRTYSEVEN,
    FileTWOHUNDREDTHIRTYEIGHT, FileTWOHUNDREDTHIRTYNINE, FileTWOHUNDREDFORTY,
    FileTWOHUNDREDFORTYONE, FileTWOHUNDREDFORTYTWO, FileTWOHUNDREDFORTYTHREE,
    FileTWOHUNDREDFORTYFOUR, FileTWOHUNDREDFORTYFIVE, FileTWOHUNDREDFORTYSIX,
    FileTWOHUNDREDFORTYSEVEN, FileTWOHUNDREDFORTYEIGHT, FileTWOHUNDREDFORTYNINE,
    FileTWOHUNDREDFIFTY, FileTWOHUNDREDFIFTYONE, FileTWOHUNDREDFIFTYTWO,
    FileTWOHUNDREDFIFTYTHREE, FileTWOHUNDREDFIFTYFOUR, FileTWOHUNDREDFIFTYFIVE,
    FileTWOHUNDREDFIFTYSIX, FileTWOHUNDREDFIFTYSEVEN, FileTWOHUNDREDFIFTYEIGHT,
    FileTWOHUNDREDFIFTYNINE, FileTWOHUNDREDSIXTY, FileTWOHUNDREDSIXTYONE,
    FileTWOHUNDREDSIXTYTWO, FileTWOHUNDREDSIXTYTHREE, FileTWOHUNDREDSIXTYFOUR,
    FileTWOHUNDREDSIXTYFIVE, FileTWOHUNDREDSIXTYSIX, FileTWOHUNDREDSIXTYSEVEN,
    FileTWOHUNDREDSIXTYEIGHT, FileTWOHUNDREDSIXTYNINE, FileTWOHUNDREDSEVENTY,
    FileTWOHUNDREDSEVENTYONE, FileTWOHUNDREDSEVENTYTWO, FileTWOHUNDREDSEVENTYTHREE,
    FileTWOHUNDREDSEVENTYFOUR, FileTWOHUNDREDSEVENTYFIVE, FileTWOHUNDREDSEVENTYSIX,
    FileTWOHUNDREDSEVENTYSEVEN, FileTWOHUNDREDSEVENTYEIGHT, FileTWOHUNDREDSEVENTYNINE,
    FileTWOHUNDREDEIGHTY, FileTWOHUNDREDEIGHTYONE, FileTWOHUNDREDEIGHTYTWO,
    FileTWOHUNDREDEIGHTYTHREE, FileTWOHUNDREDEIGHTYFOUR, FileTWOHUNDREDEIGHTYFIVE,
    FileTWOHUNDREDEIGHTYSIX, FileTWOHUNDREDEIGHTYSEVEN, FileTWOHUNDREDEIGHTYEIGHT,
    FileTWOHUNDREDEIGHTYNINE, FileTWOHUNDREDNINETY, FileTWOHUNDREDNINETYONE,
    FileTWOHUNDREDNINETYTWO, FileTWOHUNDREDNINETYTHREE, FileTWOHUNDREDNINETYFOUR,
    FileTWOHUNDREDNINETYFIVE, FileTWOHUNDREDNINETYSIX, FileTWOHUNDREDNINETYSEVEN,
    FileTWOHUNDREDNINETYEIGHT, FileTWOHUNDREDNINETYNINE, FileTHREEHUNDRED,
    FileTHREEHUNDREDONE, FileTHREEHUNDREDTWO, FileTHREEHUNDREDTHREE,
    FileTHREEHUNDREDFOR, FileTHREEHUNDREDFIVE, FileTHREEHUNDREDSIX,
    FileTHREEHUNDREDSEVEN, FileTHREEHUNDREDEIGHT, FileTHREEHUNDREDNINE,
    FileTHREEHUNDREDTEN, FileTHREEHUNDREDELEVEN, FileTHREEHUNDREDTWELVE,
    FileTHREEHUNDREDTHIRTEEN, FileTHREEHUNDREDFORTEEN, FileTHREEHUNDFIFTEEN,
    FileTHREEHUNDREDSIXTEEN, FileTHREEHUNDREDSEVENTEEN, FileTHREEHUNDREDEIGHTEEN,
    FileTHREEHUNDREDNINETEEN, FileTHREEHUNDREDTWENTY, FileTHREEHUNDREDTWENTYONE,
    FileTHREEHUNDREDTWENTYTWO, FileTHREEHUNDREDTWENTYTHREE, FileTHREEHUNDREDTWENTYFOUR,
    FileTHREEHUNDREDTWENTYFIVE, FileTHREEHUNDREDTWENTYSIX, FileTHREEHUNDREDTWENTYSEVEN,
    FileTHREEHUNDREDTWENTYEIGHT, FileTHREEHUNDREDTWENTYNINE, FileTHREEHUNDREDTHIRTY,
    FileTHREEHUNDREDTHIRTYONE, FileTHREEHUNDREDTHIRTYTWO, FileTHREEHUNDREDTHIRTYTHREE,
    FileTHREEHUNDREDTHIRTYFOUR, FileTHREEHUNDREDTHIRTYFIVE, FileTHREEHUNDREDTHIRTYSIX,
    FileTHREEHUNDREDTHIRTYSEVEN, FileTHREEHUNDREDTHIRTYEIGHT, FileTHREEHUNDREDTHIRTYNINE,
    FileTHREEHUNDREDFORTY, FileTHREEHUNDREDFORTYONE, FileTHREEHUNDREDFORTYTWO,
    FileTHREEHUNDREDFORTYTHREE, FileTHREEHUNDREDFORTYFOUR, FileTHREEHUNDREDFORTYFIVE,
    FileTHREEHUNDREDFORTYSIX, FileTHREEHUNDREDFORTYSEVEN, FileTHREEHUNDREDFORTYEIGHT,
    FileTHREEHUNDREDFORTYNINE, FileTHREEHUNDREDFIFTY, FileTHREEHUNDREDFIFTYONE,
    FileTHREEHUNDREDFIFTYTWO, FileTHREEHUNDREDFIFTYTHREE, FileTHREEHUNDREDFIFTYFOUR,
    FileTHREEHUNDREDFIFTYFIVE, FileTHREEHUNDREDFIFTYSIX, FileTHREEHUNDREDFIFTYSEVEN,
    FileTHREEHUNDREDFIFTYEIGHT, FileTHREEHUNDREDFIFTYNINE, FileTHREEHUNDREDSIXTY,
    FileTHREEHUNDREDSIXTYONE, FileTHREEHUNDREDSIXTYTWO, FileTHREEHUNDREDSIXTYTHREE,
    FileTHREEHUNDREDSIXTYFOUR, FileTHREEHUNDREDSIXTYFIVE, FileTHREEHUNDREDSIXTYSIX,
    FileTHREEHUNDREDSIXTYSEVEN, FileTHREEHUNDREDSIXTYEIGHT, FileTHREEHUNDREDSIXTYNINE,
    FileTHREEHUNDREDSEVENTY, FileTHREEHUNDREDSEVENTYONE, FileTHREEHUNDREDSEVENTYTWO,
    FileTHREEHUNDREDSEVENTYTHREE, FileTHREEHUNDREDSEVENTYFOUR, FileTHREEHUNDREDSEVENTYFIVE,
    FileTHREEHUNDREDSEVENTYSIX, FileTHREEHUNDREDSEVENTYSEVEN, FileTHREEHUNDREDSEVENTYEIGHT,
    FileTHREEHUNDREDSEVENTYNINE, FileTHREEHUNDREDEIGHTY, FileTHREEHUNDREDEIGHTYONE,
    FileTHREEHUNDREDEIGHTYTWO, FileTHREEHUNDREDEIGHTYTHREE, FileTHREEHUNDREDEIGHTYFOUR,
    FileTHREEHUNDREDEIGHTYFIVE, FileTHREEHUNDREDEIGHTYSIX, FileTHREEHUNDREDEIGHTYSEVEN,
    FileTHREEHUNDREDEIGHTYEIGHT, FileTHREEHUNDREDEIGHTYNINE, FileTHREEHUNDREDNINETY,
    FileTHREEHUNDREDNINETYONE, FileTHREEHUNDREDNINETYTWO, FileTHREEHUNDREDNINETYTHREE,
    FileTHREEHUNDREDNINETYFOUR, FileTHREEHUNDREDNINETYFIVE, FileTHREEHUNDREDNINETYSIX,
    FileTHREEHUNDREDNINETYSEVEN, FileTHREEHUNDREDNINETYEIGHT, FileTHREEHUNDREDNINETYNINE,
    FileFOURHUNDRED, FileFOURHUNDREDONE, FileFOURHUNDREDTWO, FileFOURHUNDREDTHREE,
    FileFOURHUNDREDFOR, FileFOURHUNDREDFIVE, FileFOURHUNDREDSIX, FileFOURHUNDREDSEVEN,
    FileFOURHUNDREDEIGHT, FileFOURHUNDREDNINE, FileFOURHUNDREDTEN, FileFOURHUNDREDELEVEN,
    FileFOURHUNDREDTWELVE, FileFOURHUNDREDTHIRTEEN, FileFOURHUNDREDFORTEEN,
    FileFOURHUNDFIFTEEN, FileFOURHUNDREDSIXTEEN, FileFOURHUNDREDSEVENTEEN,
    FileFOURHUNDREDEIGHTEEN, FileFOURHUNDREDNINETEEN, FileFOURHUNDREDTWENTY,
    FileFOURHUNDREDTWENTYONE, FileFOURHUNDREDTWENTYTWO, FileFOURHUNDREDTWENTYTHREE,
    FileFOURHUNDREDTWENTYFOUR, FileFOURHUNDREDTWENTYFIVE, FileFOURHUNDREDTWENTYSIX,
    FileFOURHUNDREDTWENTYSEVEN, FileFOURHUNDREDTWENTYEIGHT, FileFOURHUNDREDTWENTYNINE,
    FileFOURHUNDREDTHIRTY, FileFOURHUNDREDTHIRTYONE, FileFOURHUNDREDTHIRTYTWO,
    FileFOURHUNDREDTHIRTYTHREE, FileFOURHUNDREDTHIRTYFOUR, FileFOURHUNDREDTHIRTYFIVE,
    FileFOURHUNDREDTHIRTYSIX, FileFOURHUNDREDTHIRTYSEVEN, FileFOURHUNDREDTHIRTYEIGHT,
    FileFOURHUNDREDTHIRTYNINE, FileFOURHUNDREDFORTY, FileFOURHUNDREDFORTYONE,
    FileFOURHUNDREDFORTYTWO, FileFOURHUNDREDFORTYTHREE, FileFOURHUNDREDFORTYFOUR,
    FileFOURHUNDREDFORTYFIVE, FileFOURHUNDREDFORTYSIX, FileFOURHUNDREDFORTYSEVEN,
    FileFOURHUNDREDFORTYEIGHT, FileFOURHUNDREDFORTYNINE, FileFOURHUNDREDFIFTY,
    FileFOURHUNDREDFIFTYONE, FileFOURHUNDREDFIFTYTWO, FileFOURHUNDREDFIFTYTHREE,
    FileFOURHUNDREDFIFTYFOUR, FileFOURHUNDREDFIFTYFIVE, FileFOURHUNDREDFIFTYSIX,
    FileFOURHUNDREDFIFTYSEVEN, FileFOURHUNDREDFIFTYEIGHT, FileFOURHUNDREDFIFTYNINE,
    FileFOURHUNDREDSIXTY, FileFOURHUNDREDSIXTYONE, FileFOURHUNDREDSIXTYTWO,
    FileFOURHUNDREDSIXTYTHREE, FileFOURHUNDREDSIXTYFOUR, FileFOURHUNDREDSIXTYFIVE,
    FileFOURHUNDREDSIXTYSIX, FileFOURHUNDREDSIXTYSEVEN, FileFOURHUNDREDSIXTYEIGHT,
    FileFOURHUNDREDSIXTYNINE, FileFOURHUNDREDSEVENTY, FileFOURHUNDREDSEVENTYONE,
    FileFOURHUNDREDSEVENTYTWO, FileFOURHUNDREDSEVENTYTHREE, FileFOURHUNDREDSEVENTYFOUR,
    FileFOURHUNDREDSEVENTYFIVE, FileFOURHUNDREDSEVENTYSIX, FileFOURHUNDREDSEVENTYSEVEN,
    FileFOURHUNDREDSEVENTYEIGHT, FileFOURHUNDREDSEVENTYNINE, FileFOURHUNDREDEIGHTY,
    FileFOURHUNDREDEIGHTYONE, FileFOURHUNDREDEIGHTYTWO, FileFOURHUNDREDEIGHTYTHREE,
    FileFOURHUNDREDEIGHTYFOUR, FileFOURHUNDREDEIGHTYFIVE, FileFOURHUNDREDEIGHTYSIX,
    FileFOURHUNDREDEIGHTYSEVEN, FileFOURHUNDREDEIGHTYEIGHT, FileFOURHUNDREDEIGHTYNINE,
    FileFOURHUNDREDNINETY, FileFOURHUNDREDNINETYONE, FileFOURHUNDREDNINETYTWO,
    FileFOURHUNDREDNINETYTHREE, FileFOURHUNDREDNINETYFOUR, FileFOURHUNDREDNINETYFIVE,
    FileFOURHUNDREDNINETYSIX, FileFOURHUNDREDNINETYSEVEN, FileFOURHUNDREDNINETYEIGHT,
    FileFOURHUNDREDNINETYNINE, FileFIVEHUNDRED, FileFIVEHUNDREDONE, FileFIVEHUNDREDTWO,
    FileFIVEHUNDREDTHREE, FileFIVEHUNDREDFOR, FileFIVEHUNDREDFIVE, FileFIVEHUNDREDSIX,
    FileFIVEHUNDREDSEVEN, FileFIVEHUNDREDEIGHT, FileFIVEHUNDREDNINE, FileFIVEHUNDREDTEN,
    FileFIVEHUNDREDELEVEN, FileFIVEHUNDREDTWELVE, FileFIVEHUNDREDTHIRTEEN,
    FileFIVEHUNDREDFORTEEN, FileFIVEHUNDFIFTEEN, FileFIVEHUNDREDSIXTEEN,
    FileFIVEHUNDREDSEVENTEEN, FileFIVEHUNDREDEIGHTEEN, FileFIVEHUNDREDNINETEEN,
    FileFIVEHUNDREDTWENTY, FileFIVEHUNDREDTWENTYONE, FileFIVEHUNDREDTWENTYTWO,
    FileFIVEHUNDREDTWENTYTHREE, FileFIVEHUNDREDTWENTYFOUR, FileFIVEHUNDREDTWENTYFIVE,
    FileFIVEHUNDREDTWENTYSIX, FileFIVEHUNDREDTWENTYSEVEN, FileFIVEHUNDREDTWENTYEIGHT,
    FileFIVEHUNDREDTWENTYNINE, FileFIVEHUNDREDTHIRTY, FileFIVEHUNDREDTHIRTYONE,
    FileFIVEHUNDREDTHIRTYTWO, FileFIVEHUNDREDTHIRTYTHREE, FileFIVEHUNDREDTHIRTYFOUR,
    FileFIVEHUNDREDTHIRTYFIVE, FileFIVEHUNDREDTHIRTYSIX, FileFIVEHUNDREDTHIRTYSEVEN,
    FileFIVEHUNDREDTHIRTYEIGHT, FileFIVEHUNDREDTHIRTYNINE, FileFIVEHUNDREDFORTY,
    FileFIVEHUNDREDFORTYONE, FileFIVEHUNDREDFORTYTWO, FileFIVEHUNDREDFORTYTHREE,
    FileFIVEHUNDREDFORTYFOUR, FileFIVEHUNDREDFORTYFIVE, FileFIVEHUNDREDFORTYSIX,
    FileFIVEHUNDREDFORTYSEVEN, FileFIVEHUNDREDFORTYEIGHT, FileFIVEHUNDREDFORTYNINE,
    FileFIVEHUNDREDFIFTY, FileFIVEHUNDREDFIFTYONE, FileFIVEHUNDREDFIFTYTWO,
    FileFIVEHUNDREDFIFTYTHREE, FileFIVEHUNDREDFIFTYFOUR, FileFIVEHUNDREDFIFTYFIVE,
    FileFIVEHUNDREDFIFTYSIX, FileFIVEHUNDREDFIFTYSEVEN, FileFIVEHUNDREDFIFTYEIGHT,
    FileFIVEHUNDREDFIFTYNINE, FileFIVEHUNDREDSIXTY, FileFIVEHUNDREDSIXTYONE,
    FileFIVEHUNDREDSIXTYTWO, FileFIVEHUNDREDSIXTYTHREE, FileFIVEHUNDREDSIXTYFOUR,
    FileFIVEHUNDREDSIXTYFIVE, FileFIVEHUNDREDSIXTYSIX, FileFIVEHUNDREDSIXTYSEVEN,
    FileFIVEHUNDREDSIXTYEIGHT, FileFIVEHUNDREDSIXTYNINE, FileFIVEHUNDREDSEVENTY,
    FileFIVEHUNDREDSEVENTYONE, FileFIVEHUNDREDSEVENTYTWO, FileFIVEHUNDREDSEVENTYTHREE,
    FileFIVEHUNDREDSEVENTYFOUR, FileFIVEHUNDREDSEVENTYFIVE, FileFIVEHUNDREDSEVENTYSIX,
    FileFIVEHUNDREDSEVENTYSEVEN, FileFIVEHUNDREDSEVENTYEIGHT, FileFIVEHUNDREDSEVENTYNINE,
    FileFIVEHUNDREDEIGHTY, FileFIVEHUNDREDEIGHTYONE, FileFIVEHUNDREDEIGHTYTWO,
    FileFIVEHUNDREDEIGHTYTHREE, FileFIVEHUNDREDEIGHTYFOUR, FileFIVEHUNDREDEIGHTYFIVE,
    FileFIVEHUNDREDEIGHTYSIX, FileFIVEHUNDREDEIGHTYSEVEN, FileFIVEHUNDREDEIGHTYEIGHT,
    FileFIVEHUNDREDEIGHTYNINE, FileFIVEHUNDREDNINETY, FileFIVEHUNDREDNINETYONE,
    FileFIVEHUNDREDNINETYTWO, FileFIVEHUNDREDNINETYTHREE, FileFIVEHUNDREDNINETYFOUR,
    FileFIVEHUNDREDNINETYFIVE, FileFIVEHUNDREDNINETYSIX, FileFIVEHUNDREDNINETYSEVEN,
    FileFIVEHUNDREDNINETYEIGHT, FileFIVEHUNDREDNINETYNINE, FileSIXHUNDRED,
    FileSIXHUNDREDONE, FileSIXHUNDREDTWO, FileSIXHUNDREDTHREE, FileSIXHUNDREDFOR,
    FileSIXHUNDREDFIVE, FileSIXHUNDREDSIX, FileSIXHUNDREDSEVEN, FileSIXHUNDREDEIGHT,
    FileSIXHUNDREDNINE, FileSIXHUNDREDTEN, FileSIXHUNDREDELEVEN, FileSIXHUNDREDTWELVE,
    FileSIXHUNDREDTHIRTEEN, FileSIXHUNDREDFORTEEN, FileSIXHUNDFIFTEEN, FileSIXHUNDREDSIXTEEN,
    FileSIXHUNDREDSEVENTEEN, FileSIXHUNDREDEIGHTEEN, FileSIXHUNDREDNINETEEN, FileSIXHUNDREDTWENTY,
    FileSIXHUNDREDTWENTYONE, FileSIXHUNDREDTWENTYTWO, FileSIXHUNDREDTWENTYTHREE,
    FileSIXHUNDREDTWENTYFOUR, FileSIXHUNDREDTWENTYFIVE, FileSIXHUNDREDTWENTYSIX,
    FileSIXHUNDREDTWENTYSEVEN, FileSIXHUNDREDTWENTYEIGHT, FileSIXHUNDREDTWENTYNINE,
    FileSIXHUNDREDTHIRTY, FileSIXHUNDREDTHIRTYONE, FileSIXHUNDREDTHIRTYTWO,
    FileSIXHUNDREDTHIRTYTHREE, FileSIXHUNDREDTHIRTYFOUR, FileSIXHUNDREDTHIRTYFIVE,
    FileSIXHUNDREDTHIRTYSIX, FileSIXHUNDREDTHIRTYSEVEN, FileSIXHUNDREDTHIRTYEIGHT,
    FileSIXHUNDREDTHIRTYNINE, FileSIXHUNDREDFORTY, FileSIXHUNDREDFORTYONE,
    FileSIXHUNDREDFORTYTWO, FileSIXHUNDREDFORTYTHREE, FileSIXHUNDREDFORTYFOUR,
    FileSIXHUNDREDFORTYFIVE, FileSIXHUNDREDFORTYSIX, FileSIXHUNDREDFORTYSEVEN,
    FileSIXHUNDREDFORTYEIGHT, FileSIXHUNDREDFORTYNINE, FileSIXHUNDREDFIFTY,
    FileSIXHUNDREDFIFTYONE, FileSIXHUNDREDFIFTYTWO, FileSIXHUNDREDFIFTYTHREE,
    FileSIXHUNDREDFIFTYFOUR, FileSIXHUNDREDFIFTYFIVE, FileSIXHUNDREDFIFTYSIX,
    FileSIXHUNDREDFIFTYSEVEN, FileSIXHUNDREDFIFTYEIGHT, FileSIXHUNDREDFIFTYNINE,
    FileSIXHUNDREDSIXTY, FileSIXHUNDREDSIXTYONE, FileSIXHUNDREDSIXTYTWO,
    FileSIXHUNDREDSIXTYTHREE, FileSIXHUNDREDSIXTYFOUR, FileSIXHUNDREDSIXTYFIVE,
    FileSIXHUNDREDSIXTYSIX, FileSIXHUNDREDSIXTYSEVEN, FileSIXHUNDREDSIXTYEIGHT,
    FileSIXHUNDREDSIXTYNINE, FileSIXHUNDREDSEVENTY, FileSIXHUNDREDSEVENTYONE,
    FileSIXHUNDREDSEVENTYTWO, FileSIXHUNDREDSEVENTYTHREE, FileSIXHUNDREDSEVENTYFOUR,
    FileSIXHUNDREDSEVENTYFIVE, FileSIXHUNDREDSEVENTYSIX, FileSIXHUNDREDSEVENTYSEVEN,
    FileSIXHUNDREDSEVENTYEIGHT, FileSIXHUNDREDSEVENTYNINE, FileSIXHUNDREDEIGHTY,
    FileSIXHUNDREDEIGHTYONE, FileSIXHUNDREDEIGHTYTWO, FileSIXHUNDREDEIGHTYTHREE,
    FileSIXHUNDREDEIGHTYFOUR, FileSIXHUNDREDEIGHTYFIVE, FileSIXHUNDREDEIGHTYSIX,
    FileSIXHUNDREDEIGHTYSEVEN, FileSIXHUNDREDEIGHTYEIGHT, FileSIXHUNDREDEIGHTYNINE,
    FileSIXHUNDREDNINETY, FileSIXHUNDREDNINETYONE, FileSIXHUNDREDNINETYTWO,
    FileSIXHUNDREDNINETYTHREE, FileSIXHUNDREDNINETYFOUR, FileSIXHUNDREDNINETYFIVE,
    FileSIXHUNDREDNINETYSIX, FileSIXHUNDREDNINETYSEVEN, FileSIXHUNDREDNINETYEIGHT,
    FileSIXHUNDREDNINETYNINE, FileSEVENHUNDRED, FileSEVENHUNDREDONE, FileSEVENHUNDREDTWO,
    FileSEVENHUNDREDTHREE, FileSEVENHUNDREDFOR, FileSEVENHUNDREDFIVE, FileSEVENHUNDREDSIX,
    FileSEVENHUNDREDSEVEN, FileSEVENHUNDREDEIGHT, FileSEVENHUNDREDNINE, FileSEVENHUNDREDTEN,
    FileSEVENHUNDREDELEVEN, FileSEVENHUNDREDTWELVE, FileSEVENHUNDREDTHIRTEEN,
    FileSEVENHUNDREDFORTEEN, FileSEVENHUNDFIFTEEN, FileSEVENHUNDREDSIXTEEN,
    FileSEVENHUNDREDSEVENTEEN, FileSEVENHUNDREDEIGHTEEN, FileSEVENHUNDREDNINETEEN,
    FileSEVENHUNDREDTWENTY, FileSEVENHUNDREDTWENTYONE, FileSEVENHUNDREDTWENTYTWO,
    FileSEVENHUNDREDTWENTYTHREE, FileSEVENHUNDREDTWENTYFOUR, FileSEVENHUNDREDTWENTYFIVE,
    FileSEVENHUNDREDTWENTYSIX, FileSEVENHUNDREDTWENTYSEVEN, FileSEVENHUNDREDTWENTYEIGHT,
    FileSEVENHUNDREDTWENTYNINE, FileSEVENHUNDREDTHIRTY, FileSEVENHUNDREDTHIRTYONE,
    FileSEVENHUNDREDTHIRTYTWO, FileSEVENHUNDREDTHIRTYTHREE, FileSEVENHUNDREDTHIRTYFOUR,
    FileSEVENHUNDREDTHIRTYFIVE, FileSEVENHUNDREDTHIRTYSIX, FileSEVENHUNDREDTHIRTYSEVEN,
    FileSEVENHUNDREDTHIRTYEIGHT, FileSEVENHUNDREDTHIRTYNINE, FileSEVENHUNDREDFORTY,
    FileSEVENHUNDREDFORTYONE, FileSEVENHUNDREDFORTYTWO, FileSEVENHUNDREDFORTYTHREE,
    FileSEVENHUNDREDFORTYFOUR, FileSEVENHUNDREDFORTYFIVE, FileSEVENHUNDREDFORTYSIX,
    FileSEVENHUNDREDFORTYSEVEN, FileSEVENHUNDREDFORTYEIGHT, FileSEVENHUNDREDFORTYNINE,
    FileSEVENHUNDREDFIFTY, FileSEVENHUNDREDFIFTYONE, FileSEVENHUNDREDFIFTYTWO,
    FileSEVENHUNDREDFIFTYTHREE, FileSEVENHUNDREDFIFTYFOUR, FileSEVENHUNDREDFIFTYFIVE,
    FileSEVENHUNDREDFIFTYSIX, FileSEVENHUNDREDFIFTYSEVEN, FileSEVENHUNDREDFIFTYEIGHT,
    FileSEVENHUNDREDFIFTYNINE, FileSEVENHUNDREDSIXTY, FileSEVENHUNDREDSIXTYONE,
    FileSEVENHUNDREDSIXTYTWO, FileSEVENHUNDREDSIXTYTHREE, FileSEVENHUNDREDSIXTYFOUR,
    FileSEVENHUNDREDSIXTYFIVE, FileSEVENHUNDREDSIXTYSIX, FileSEVENHUNDREDSIXTYSEVEN,
    FileSEVENHUNDREDSIXTYEIGHT, FileSEVENHUNDREDSIXTYNINE, FileSEVENHUNDREDSEVENTY,
    FileSEVENHUNDREDSEVENTYONE, FileSEVENHUNDREDSEVENTYTWO, FileSEVENHUNDREDSEVENTYTHREE,
    FileSEVENHUNDREDSEVENTYFOUR, FileSEVENHUNDREDSEVENTYFIVE, FileSEVENHUNDREDSEVENTYSIX,
    FileSEVENHUNDREDSEVENTYSEVEN, FileSEVENHUNDREDSEVENTYEIGHT, FileSEVENHUNDREDSEVENTYNINE,
    FileSEVENHUNDREDEIGHTY, FileSEVENHUNDREDEIGHTYONE, FileSEVENHUNDREDEIGHTYTWO,
    FileSEVENHUNDREDEIGHTYTHREE, FileSEVENHUNDREDEIGHTYFOUR, FileSEVENHUNDREDEIGHTYFIVE,
    FileSEVENHUNDREDEIGHTYSIX, FileSEVENHUNDREDEIGHTYSEVEN, FileSEVENHUNDREDEIGHTYEIGHT,
    FileSEVENHUNDREDEIGHTYNINE, FileSEVENHUNDREDNINETY, FileSEVENHUNDREDNINETYONE,
    FileSEVENHUNDREDNINETYTWO, FileSEVENHUNDREDNINETYTHREE, FileSEVENHUNDREDNINETYFOUR,
    FileSEVENHUNDREDNINETYFIVE, FileSEVENHUNDREDNINETYSIX, FileSEVENHUNDREDNINETYSEVEN,
    FileSEVENHUNDREDNINETYEIGHT, FileSEVENHUNDREDNINETYNINE, FileEIGHTHUNDRED,
    FileEIGHTHUNDREDONE, FileEIGHTHUNDREDTWO, FileEIGHTHUNDREDTHREE, FileEIGHTHUNDREDFOR,
    FileEIGHTHUNDREDFIVE, FileEIGHTHUNDREDSIX, FileEIGHTHUNDREDSEVEN, FileEIGHTHUNDREDEIGHT,
    FileEIGHTHUNDREDNINE, FileEIGHTHUNDREDTEN, FileEIGHTHUNDREDELEVEN, FileEIGHTHUNDREDTWELVE,
    FileEIGHTHUNDREDTHIRTEEN, FileEIGHTHUNDREDFORTEEN, FileEIGHTHUNDFIFTEEN, FileEIGHTHUNDREDSIXTEEN,
    FileEIGHTHUNDREDSEVENTEEN, FileEIGHTHUNDREDEIGHTEEN, FileEIGHTHUNDREDNINETEEN, FileEIGHTHUNDREDTWENTY,
    FileEIGHTHUNDREDTWENTYONE, FileEIGHTHUNDREDTWENTYTWO, FileEIGHTHUNDREDTWENTYTHREE,
    FileEIGHTHUNDREDTWENTYFOUR, FileEIGHTHUNDREDTWENTYFIVE, FileEIGHTHUNDREDTWENTYSIX,
    FileEIGHTHUNDREDTWENTYSEVEN, FileEIGHTHUNDREDTWENTYEIGHT, FileEIGHTHUNDREDTWENTYNINE,
    FileEIGHTHUNDREDTHIRTY, FileEIGHTHUNDREDTHIRTYONE, FileEIGHTHUNDREDTHIRTYTWO,
    FileEIGHTHUNDREDTHIRTYTHREE, FileEIGHTHUNDREDTHIRTYFOUR, FileEIGHTHUNDREDTHIRTYFIVE,
    FileEIGHTHUNDREDTHIRTYSIX, FileEIGHTHUNDREDTHIRTYSEVEN, FileEIGHTHUNDREDTHIRTYEIGHT,
    FileEIGHTHUNDREDTHIRTYNINE, FileEIGHTHUNDREDFORTY, FileEIGHTHUNDREDFORTYONE,
    FileEIGHTHUNDREDFORTYTWO, FileEIGHTHUNDREDFORTYTHREE, FileEIGHTHUNDREDFORTYFOUR,
    FileEIGHTHUNDREDFORTYFIVE, FileEIGHTHUNDREDFORTYSIX, FileEIGHTHUNDREDFORTYSEVEN,
    FileEIGHTHUNDREDFORTYEIGHT, FileEIGHTHUNDREDFORTYNINE, FileEIGHTHUNDREDFIFTY,
    FileEIGHTHUNDREDFIFTYONE, FileEIGHTHUNDREDFIFTYTWO, FileEIGHTHUNDREDFIFTYTHREE,
    FileEIGHTHUNDREDFIFTYFOUR, FileEIGHTHUNDREDFIFTYFIVE, FileEIGHTHUNDREDFIFTYSIX,
    FileEIGHTHUNDREDFIFTYSEVEN, FileEIGHTHUNDREDFIFTYEIGHT, FileEIGHTHUNDREDFIFTYNINE,
    FileEIGHTHUNDREDSIXTY, FileEIGHTHUNDREDSIXTYONE, FileEIGHTHUNDREDSIXTYTWO,
    FileEIGHTHUNDREDSIXTYTHREE, FileEIGHTHUNDREDSIXTYFOUR, FileEIGHTHUNDREDSIXTYFIVE,
    FileEIGHTHUNDREDSIXTYSIX, FileEIGHTHUNDREDSIXTYSEVEN, FileEIGHTHUNDREDSIXTYEIGHT,
    FileEIGHTHUNDREDSIXTYNINE, FileEIGHTHUNDREDSEVENTY, FileEIGHTHUNDREDSEVENTYONE,
    FileEIGHTHUNDREDSEVENTYTWO, FileEIGHTHUNDREDSEVENTYTHREE, FileEIGHTHUNDREDSEVENTYFOUR,
    FileEIGHTHUNDREDSEVENTYFIVE, FileEIGHTHUNDREDSEVENTYSIX, FileEIGHTHUNDREDSEVENTYSEVEN,
    FileEIGHTHUNDREDSEVENTYEIGHT, FileEIGHTHUNDREDSEVENTYNINE, FileEIGHTHUNDREDEIGHTY,
    FileEIGHTHUNDREDEIGHTYONE, FileEIGHTHUNDREDEIGHTYTWO, FileEIGHTHUNDREDEIGHTYTHREE,
    FileEIGHTHUNDREDEIGHTYFOUR, FileEIGHTHUNDREDEIGHTYFIVE, FileEIGHTHUNDREDEIGHTYSIX,
    FileEIGHTHUNDREDEIGHTYSEVEN, FileEIGHTHUNDREDEIGHTYEIGHT, FileEIGHTHUNDREDEIGHTYNINE,
    FileEIGHTHUNDREDNINETY, FileEIGHTHUNDREDNINETYONE, FileEIGHTHUNDREDNINETYTWO,
    FileEIGHTHUNDREDNINETYTHREE, FileEIGHTHUNDREDNINETYFOUR, FileEIGHTHUNDREDNINETYFIVE,
    FileEIGHTHUNDREDNINETYSIX, FileEIGHTHUNDREDNINETYSEVEN, FileEIGHTHUNDREDNINETYEIGHT,
    FileEIGHTHUNDREDNINETYNINE, FileNINEHUNDRED, FileNINEHUNDREDONE, FileNINEHUNDREDTWO,
    FileNINEHUNDREDTHREE, FileNINEHUNDREDFOR, FileNINEHUNDREDFIVE, FileNINEHUNDREDSIX,
    FileNINEHUNDREDSEVEN, FileNINEHUNDREDEIGHT, FileNINEHUNDREDNINE, FileNINEHUNDREDTEN,
    FileNINEHUNDREDELEVEN, FileNINEHUNDREDTWELVE, FileNINEHUNDREDTHIRTEEN,
    FileNINEHUNDREDFORTEEN, FileNINEHUNDFIFTEEN, FileNINEHUNDREDSIXTEEN,
    FileNINEHUNDREDSEVENTEEN, FileNINEHUNDREDEIGHTEEN, FileNINEHUNDREDNINETEEN,
    FileNINEHUNDREDTWENTY, FileNINEHUNDREDTWENTYONE, FileNINEHUNDREDTWENTYTWO,
    FileNINEHUNDREDTWENTYTHREE, FileNINEHUNDREDTWENTYFOUR, FileNINEHUNDREDTWENTYFIVE,
    FileNINEHUNDREDTWENTYSIX, FileNINEHUNDREDTWENTYSEVEN, FileNINEHUNDREDTWENTYEIGHT,
    FileNINEHUNDREDTWENTYNINE, FileNINEHUNDREDTHIRTY, FileNINEHUNDREDTHIRTYONE,
    FileNINEHUNDREDTHIRTYTWO, FileNINEHUNDREDTHIRTYTHREE, FileNINEHUNDREDTHIRTYFOUR,
    FileNINEHUNDREDTHIRTYFIVE, FileNINEHUNDREDTHIRTYSIX, FileNINEHUNDREDTHIRTYSEVEN,
    FileNINEHUNDREDTHIRTYEIGHT, FileNINEHUNDREDTHIRTYNINE, FileNINEHUNDREDFORTY,
    FileNINEHUNDREDFORTYONE, FileNINEHUNDREDFORTYTWO, FileNINEHUNDREDFORTYTHREE,
    FileNINEHUNDREDFORTYFOUR, FileNINEHUNDREDFORTYFIVE, FileNINEHUNDREDFORTYSIX,
    FileNINEHUNDREDFORTYSEVEN, FileNINEHUNDREDFORTYEIGHT, FileNINEHUNDREDFORTYNINE,
    FileNINEHUNDREDFIFTY, FileNINEHUNDREDFIFTYONE, FileNINEHUNDREDFIFTYTWO,
    FileNINEHUNDREDFIFTYTHREE, FileNINEHUNDREDFIFTYFOUR, FileNINEHUNDREDFIFTYFIVE,
    FileNINEHUNDREDFIFTYSIX, FileNINEHUNDREDFIFTYSEVEN, FileNINEHUNDREDFIFTYEIGHT,
    FileNINEHUNDREDFIFTYNINE, FileNINEHUNDREDSIXTY, FileNINEHUNDREDSIXTYONE,
    FileNINEHUNDREDSIXTYTWO, FileNINEHUNDREDSIXTYTHREE, FileNINEHUNDREDSIXTYFOUR,
    FileNINEHUNDREDSIXTYFIVE, FileNINEHUNDREDSIXTYSIX, FileNINEHUNDREDSIXTYSEVEN,
    FileNINEHUNDREDSIXTYEIGHT, FileNINEHUNDREDSIXTYNINE, FileNINEHUNDREDSEVENTY,
    FileNINEHUNDREDSEVENTYONE, FileNINEHUNDREDSEVENTYTWO, FileNINEHUNDREDSEVENTYTHREE,
    FileNINEHUNDREDSEVENTYFOUR, FileNINEHUNDREDSEVENTYFIVE, FileNINEHUNDREDSEVENTYSIX,
    FileNINEHUNDREDSEVENTYSEVEN, FileNINEHUNDREDSEVENTYEIGHT, FileNINEHUNDREDSEVENTYNINE,
    FileNINEHUNDREDEIGHTY, FileNINEHUNDREDEIGHTYONE, FileNINEHUNDREDEIGHTYTWO,
    FileNINEHUNDREDEIGHTYTHREE, FileNINEHUNDREDEIGHTYFOUR, FileNINEHUNDREDEIGHTYFIVE,
    FileNINEHUNDREDEIGHTYSIX, FileNINEHUNDREDEIGHTYSEVEN, FileNINEHUNDREDEIGHTYEIGHT,
    FileNINEHUNDREDEIGHTYNINE, FileNINEHUNDREDNINETY, FileNINEHUNDREDNINETYONE,
    FileNINEHUNDREDNINETYTWO, FileNINEHUNDREDNINETYTHREE, FileNINEHUNDREDNINETYFOUR,
    FileNINEHUNDREDNINETYFIVE, FileNINEHUNDREDNINETYSIX, FileNINEHUNDREDNINETYSEVEN,
    FileNINEHUNDREDNINETYEIGHT, FileNINEHUNDREDNINETYNINE, FileONETHOUSAND
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import API from '../services/api';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, AreaChart, Area } from 'recharts';

export default function MedicationReminder() {
    const { user } = useAuth();
    const { addToast } = useToast();
    
    const [medications, setMedications] = useState([]);
    const [reminders, setReminders] = useState([]);
    const [loading, setLoading] = useState(true);
    const [showAddModal, setShowAddModal] = useState(false);
    const [editingMedication, setEditingMedication] = useState(null);
    const [notifications, setNotifications] = useState([]);
    const [adherenceStats, setAdherenceStats] = useState(null);
    const [todaySchedule, setTodaySchedule] = useState([]);
    const [upcomingRefills, setUpcomingRefills] = useState([]);
    const [searchTerm, setSearchTerm] = useState('');
    const [filterStatus, setFilterStatus] = useState('all');
    const [sortBy, setSortBy] = useState('name');

    useEffect(() => {
        fetchMedicationData();
        requestNotificationPermission();
        setupNotificationScheduler();
        
        return () => {
            if (notificationInterval) {
                clearInterval(notificationInterval);
            }
        };
    }, []);

    let notificationInterval;

    const fetchMedicationData = async () => {
        try {
            const [
                medicationsRes,
                remindersRes,
                statsRes,
                scheduleRes,
                refillsRes
            ] = await Promise.all([
                API.get(`/medications/${user.id}`),
                API.get(`/reminders/${user.id}`),
                API.get(`/medications/adherence/${user.id}`),
                API.get(`/reminders/schedule/${user.id}`),
                API.get(`/medications/refills/${user.id}`)
            ]);

            setMedications(medicationsRes.data || generateMockMedications());
            setReminders(remindersRes.data || generateMockReminders());
            setAdherenceStats(statsRes.data || generateMockAdherenceStats());
            setTodaySchedule(scheduleRes.data || generateMockTodaySchedule());
            setUpcomingRefills(refillsRes.data || generateMockUpcomingRefills());
        } catch (error) {
            console.error('Failed to fetch medication data:', error);
            setMedications(generateMockMedications());
            setReminders(generateMockReminders());
            setAdherenceStats(generateMockAdherenceStats());
            setTodaySchedule(generateMockTodaySchedule());
            setUpcomingRefills(generateMockUpcomingRefills());
        } finally {
            setLoading(false);
        }
    };

    const generateMockMedications = () => [
        {
            id: 1,
            name: 'Metformin',
            dosage: '500mg',
            frequency: 'twice-daily',
            times: ['08:00', '20:00'],
            startDate: '2024-01-01',
            endDate: '2024-12-31',
            status: 'active',
            prescribedBy: 'Dr. Sarah Johnson',
            purpose: 'Type 2 Diabetes',
            instructions: 'Take with meals',
            sideEffects: ['Nausea', 'Diarrhea'],
            interactions: ['Alcohol'],
            remainingSupply: 45,
            totalSupply: 60,
            refillDate: '2024-02-15',
            adherence: 0.85,
            color: '#3b82f6'
        },
        {
            id: 2,
            name: 'Lisinopril',
            dosage: '10mg',
            frequency: 'once-daily',
            times: ['09:00'],
            startDate: '2024-01-01',
            endDate: '2024-12-31',
            status: 'active',
            prescribedBy: 'Dr. Sarah Johnson',
            purpose: 'Hypertension',
            instructions: 'Take in the morning',
            sideEffects: ['Dizziness', 'Dry cough'],
            interactions: ['NSAIDs'],
            remainingSupply: 20,
            totalSupply: 30,
            refillDate: '2024-02-10',
            adherence: 0.92,
            color: '#10b981'
        },
        {
            id: 3,
            name: 'Vitamin D3',
            dosage: '1000 IU',
            frequency: 'once-daily',
            times: ['12:00'],
            startDate: '2024-01-01',
            endDate: '2024-12-31',
            status: 'active',
            prescribedBy: 'Dr. Sarah Johnson',
            purpose: 'Vitamin D deficiency',
            instructions: 'Take with lunch',
            sideEffects: [],
            interactions: [],
            remainingSupply: 50,
            totalSupply: 60,
            refillDate: '2024-02-20',
            adherence: 0.78,
            color: '#f59e0b'
        }
    ];

    const generateMockReminders = () => [
        {
            id: 1,
            medicationId: 1,
            medicationName: 'Metformin',
            time: '08:00',
            days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
            enabled: true,
            type: 'notification',
            sound: true,
            vibrate: true,
            snooze: 5,
            lastTaken: '2024-01-14T08:00:00Z',
            nextDose: '2024-01-15T08:00:00Z'
        },
        {
            id: 2,
            medicationId: 1,
            medicationName: 'Metformin',
            time: '20:00',
            days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
            enabled: true,
            type: 'notification',
            sound: true,
            vibrate: true,
            snooze: 5,
            lastTaken: '2024-01-14T20:00:00Z',
            nextDose: '2024-01-15T20:00:00Z'
        },
        {
            id: 3,
            medicationId: 2,
            medicationName: 'Lisinopril',
            time: '09:00',
            days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
            enabled: true,
            type: 'notification',
            sound: true,
            vibrate: true,
            snooze: 5,
            lastTaken: '2024-01-14T09:00:00Z',
            nextDose: '2024-01-15T09:00:00Z'
        }
    ];

    const generateMockAdherenceStats = () => ({
        overall: 0.85,
        weekly: [
            { day: 'Mon', adherence: 0.9 },
            { day: 'Tue', adherence: 0.8 },
            { day: 'Wed', adherence: 0.85 },
            { day: 'Thu', adherence: 0.9 },
            { day: 'Fri', adherence: 0.8 },
            { day: 'Sat', adherence: 0.85 },
            { day: 'Sun', adherence: 0.8 }
        ],
        monthly: [
            { month: 'Jan', adherence: 0.82 },
            { month: 'Feb', adherence: 0.85 },
            { month: 'Mar', adherence: 0.88 },
            { month: 'Apr', adherence: 0.85 },
            { month: 'May', adherence: 0.87 },
            { month: 'Jun', adherence: 0.85 }
        ],
        missedDoses: 12,
        takenDoses: 68,
        totalDoses: 80
    });

    const generateMockTodaySchedule = () => [
        {
            id: 1,
            medicationName: 'Metformin',
            time: '08:00',
            dosage: '500mg',
            taken: false,
            time: '08:00 AM'
        },
        {
            id: 2,
            medicationName: 'Lisinopril',
            time: '09:00',
            dosage: '10mg',
            taken: false,
            time: '09:00 AM'
        },
        {
            id: 3,
            medicationName: 'Vitamin D3',
            time: '12:00',
            dosage: '1000 IU',
            taken: false,
            time: '12:00 PM'
        },
        {
            id: 4,
            medicationName: 'Metformin',
            time: '20:00',
            dosage: '500mg',
            taken: false,
            time: '08:00 PM'
        }
    ];

    const generateMockUpcomingRefills = () => [
        {
            id: 1,
            medicationName: 'Lisinopril',
            refillDate: '2024-02-10',
            daysUntil: 26,
            remainingSupply: 20,
            totalSupply: 30,
            pharmacy: 'City Pharmacy',
            status: 'upcoming'
        },
        {
            id: 2,
            medicationName: 'Metformin',
            refillDate: '2024-02-15',
            daysUntil: 31,
            remainingSupply: 45,
            totalSupply: 60,
            pharmacy: 'City Pharmacy',
            status: 'upcoming'
        },
        {
            id: 3,
            medicationName: 'Vitamin D3',
            refillDate: '2024-02-20',
            daysUntil: 36,
            remainingSupply: 50,
            totalSupply: 60,
            pharmacy: 'City Pharmacy',
            status: 'upcoming'
        }
    ];

    const requestNotificationPermission = async () => {
        if ('Notification' in window) {
            const permission = await Notification.requestPermission();
            if (permission === 'granted') {
                addToast({
                    type: 'success',
                    title: 'Notifications Enabled',
                    message: 'You will receive medication reminders.'
                });
            }
        }
    };

    const setupNotificationScheduler = () => {
        // Check for upcoming doses every minute
        notificationInterval = setInterval(() => {
            checkUpcomingDoses();
        }, 60000);
    };

    const checkUpcomingDoses = () => {
        const now = new Date();
        const currentTime = now.toTimeString().slice(0, 5);
        
        reminders.forEach(reminder => {
            if (reminder.enabled && reminder.time === currentTime) {
                const today = now.toLocaleLowerCase().slice(0, 3);
                if (reminder.days.includes(today)) {
                    sendNotification(reminder);
                }
            }
        });
    };

    const sendNotification = (reminder) => {
        if ('Notification' in window && Notification.permission === 'granted') {
            const notification = new Notification('Medication Reminder', {
                body: `Time to take ${reminder.medicationName}`,
                icon: '/pill-icon.png',
                badge: '/pill-badge.png',
                tag: `medication-${reminder.id}`,
                requireInteraction: true,
                actions: [
                    {
                        action: 'take',
                        title: 'Take Now'
                    },
                    {
                        action: 'snooze',
                        title: 'Snooze'
                    }
                ]
            });

            notification.onclick = () => {
                window.focus();
                notification.close();
            };

            notification.onshow = () => {
                // Play sound if enabled
                if (reminder.sound) {
                    playNotificationSound();
                }
            };
        }
    };

    const playNotificationSound = () => {
        const audio = new Audio('/notification.mp3');
        audio.volume = 0.5;
        audio.play().catch(() => {});
    };

    const markMedicationTaken = async (scheduleId) => {
        try {
            await API.post(`/reminders/take/${scheduleId}`);
            
            setTodaySchedule(prev => 
                prev.map(schedule => 
                    schedule.id === scheduleId 
                        ? { ...schedule, taken: true, takenAt: new Date().toISOString() }
                        : schedule
                )
            );

            addToast({
                type: 'success',
                title: 'Medication Taken',
                message: 'Great job! Keep up the good work.'
            });

            fetchMedicationData();
        } catch (error) {
            console.error('Failed to mark medication as taken:', error);
        }
    };

    const snoozeMedication = async (scheduleId, minutes = 5) => {
        try {
            await API.post(`/reminders/snooze/${scheduleId}`, { minutes });
            
            addToast({
                type: 'info',
                title: 'Reminder Snoozed',
                message: `You will be reminded in ${minutes} minutes.`
            });

            fetchMedicationData();
        } catch (error) {
            console.error('Failed to snooze reminder:', error);
        }
    };

    const addMedication = async (medicationData) => {
        try {
            const response = await API.post('/medications', {
                ...medicationData,
                userId: user.id
            });

            setMedications(prev => [...prev, response.data]);
            setShowAddModal(false);
            
            addToast({
                type: 'success',
                title: 'Medication Added',
                message: 'Your medication has been added successfully.'
            });

            fetchMedicationData();
        } catch (error) {
            console.error('Failed to add medication:', error);
            addToast({
                type: 'error',
                title: 'Error',
                message: 'Failed to add medication. Please try again.'
            });
        }
    };

    const updateMedication = async (id, medicationData) => {
        try {
            await API.put(`/medications/${id}`, medicationData);
            
            setMedications(prev => 
                prev.map(med => 
                    med.id === id ? { ...med, ...medicationData } : med
                )
            );

            setEditingMedication(null);
            
            addToast({
                type: 'success',
                title: 'Medication Updated',
                message: 'Your medication has been updated successfully.'
            });

            fetchMedicationData();
        } catch (error) {
            console.error('Failed to update medication:', error);
            addToast({
                type: 'error',
                title: 'Error',
                message: 'Failed to update medication. Please try again.'
            });
        }
    };

    const deleteMedication = async (id) => {
        try {
            await API.delete(`/medications/${id}`);
            
            setMedications(prev => prev.filter(med => med.id !== id));
            
            addToast({
                type: 'success',
                title: 'Medication Deleted',
                message: 'The medication has been removed from your list.'
            });

            fetchMedicationData();
        } catch (error) {
            console.error('Failed to delete medication:', error);
            addToast({
                type: 'error',
                title: 'Error',
                message: 'Failed to delete medication. Please try again.'
            });
        }
    };

    const getAdherenceColor = (adherence) => {
        if (adherence >= 0.9) return 'text-green-400';
        if (adherence >= 0.7) return 'text-yellow-400';
        return 'text-red-400';
    };

    const getRefillStatusColor = (daysUntil) => {
        if (daysUntil <= 7) return 'text-red-400 bg-red-400/10 border-red-400/30';
        if (daysUntil <= 14) return 'text-yellow-400 bg-yellow-400/10 border-yellow-400/30';
        return 'text-green-400 bg-green-400/10 border-green-400/30';
    };

    const filteredMedications = medications.filter(med => {
        const matchesSearch = med.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                            med.purpose.toLowerCase().includes(searchTerm.toLowerCase());
        const matchesStatus = filterStatus === 'all' || med.status === filterStatus;
        return matchesSearch && matchesStatus;
    });

    const sortedMedications = [...filteredMedications].sort((a, b) => {
        switch (sortBy) {
            case 'name': return a.name.localeCompare(b.name);
            case 'nextDose': return new Date(a.nextDose) - new Date(b.nextDose);
            case 'adherence': return b.adherence - a.adherence;
            case 'refill': return new Date(a.refillDate) - new Date(b.refillDate);
            default: return 0;
        }
    });

    if (loading) {
        return (
            <div className="min-h-screen bg-[#020617] flex items-center justify-center">
                <div className="w-12 h-12 border-4 border-blue-500/20 border-t-blue-500 rounded-full animate-spin"></div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-[#020617] text-white p-4 md:p-8">
            {/* Background Effects */}
            <div className="absolute top-0 left-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-[120px] pointer-events-none"></div>
            <div className="absolute bottom-1/4 right-0 w-80 h-80 bg-purple-500/10 rounded-full blur-[100px] pointer-events-none"></div>

            <div className="max-w-7xl mx-auto relative z-10">
                {/* Header */}
                <motion.div 
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex items-center justify-between mb-8"
                >
                    <div>
                        <h1 className="text-4xl font-black text-white tracking-tight mb-2">
                            Medication <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">Reminder</span>
                        </h1>
                        <p className="text-slate-500 font-bold tracking-[0.3em] text-xs uppercase">
                            SMART MEDICATION MANAGEMENT • ADHERENCE TRACKING
                        </p>
                    </div>

                    <div className="flex items-center gap-4">
                        <button
                            onClick={() => setShowAddModal(true)}
                            className="px-4 py-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl hover:from-blue-700 hover:to-purple-700 transition-all flex items-center gap-2"
                        >
                            <Plus className="w-4 h-4" />
                            Add Medication
                        </button>
                        <button className="p-2 text-slate-400 hover:text-white transition-colors">
                            <Settings className="w-5 h-5" />
                        </button>
                    </div>
                </motion.div>

                {/* Stats Overview */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8"
                >
                    <div className="bg-slate-800/50 backdrop-blur-lg border border-white/10 rounded-2xl p-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-500 rounded-xl flex items-center justify-center">
                                <Pill className="w-6 h-6 text-white" />
                            </div>
                            <span className="text-2xl font-bold text-white">{medications.length}</span>
                        </div>
                        <h3 className="text-sm font-semibold text-slate-400">Total Medications</h3>
                    </div>

                    <div className="bg-slate-800/50 backdrop-blur-lg border border-white/10 rounded-2xl p-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="w-12 h-12 bg-gradient-to-r from-green-500 to-emerald-500 rounded-xl flex items-center justify-center">
                                <CheckCircle className="w-6 h-6 text-white" />
                            </div>
                            <span className={`text-2xl font-bold ${getAdherenceColor(adherenceStats?.overall || 0)}`}>
                                {Math.round((adherenceStats?.overall || 0) * 100)}%
                            </span>
                        </div>
                        <h3 className="text-sm font-semibold text-slate-400">Adherence Rate</h3>
                    </div>

                    <div className="bg-slate-800/50 backdrop-blur-lg border border-white/10 rounded-2xl p-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="w-12 h-12 bg-gradient-to-r from-orange-500 to-red-500 rounded-xl flex items-center justify-center">
                                <Clock className="w-6 h-6 text-white" />
                            </div>
                            <span className="text-2xl font-bold text-white">{todaySchedule.filter(s => !s.taken).length}</span>
                        </div>
                        <h3 className="text-sm font-semibold text-slate-400">Pending Today</h3>
                    </div>

                    <div className="bg-slate-800/50 backdrop-blur-lg border border-white/10 rounded-2xl p-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-pink-500 rounded-xl flex items-center justify-center">
                                <RefreshCw className="w-6 h-6 text-white" />
                            </div>
                            <span className="text-2xl font-bold text-white">{upcomingRefills.length}</span>
                        </div>
                        <h3 className="text-sm font-semibold text-slate-400">Upcoming Refills</h3>
                    </div>
                </motion.div>

                {/* Today's Schedule */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                    className="bg-slate-800/50 backdrop-blur-lg border border-white/10 rounded-2xl p-6 mb-8"
                >
                    <h3 className="text-lg font-semibold text-white mb-4">Today's Schedule</h3>
                    <div className="space-y-3">
                        {todaySchedule.map((schedule, index) => (
                            <div key={schedule.id} className="flex items-center justify-between p-4 bg-slate-700/50 rounded-xl">
                                <div className="flex items-center gap-4">
                                    <div className="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-500 rounded-lg flex items-center justify-center">
                                        <Pill className="w-5 h-5 text-white" />
                                    </div>
                                    <div>
                                        <h4 className="font-semibold text-white">{schedule.medicationName}</h4>
                                        <p className="text-sm text-slate-400">{schedule.dosage} • {schedule.time}</p>
                                    </div>
                                </div>
                                <div className="flex items-center gap-2">
                                    {schedule.taken ? (
                                        <span className="px-3 py-1 bg-green-500/20 border border-green-500/30 rounded-full text-xs font-semibold text-green-400">
                                            Taken
                                        </span>
                                    ) : (
                                        <>
                                            <button
                                                onClick={() => markMedicationTaken(schedule.id)}
                                                className="px-3 py-1 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm"
                                            >
                                                Take Now
                                            </button>
                                            <button
                                                onClick={() => snoozeMedication(schedule.id)}
                                                className="px-3 py-1 bg-slate-600 text-white rounded-lg hover:bg-slate-700 transition-colors text-sm"
                                            >
                                                Snooze
                                            </button>
                                        </>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                </motion.div>

                {/* Medications List */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    className="bg-slate-800/50 backdrop-blur-lg border border-white/10 rounded-2xl p-6"
                >
                    <div className="flex items-center justify-between mb-6">
                        <h3 className="text-lg font-semibold text-white">My Medications</h3>
                        <div className="flex items-center gap-4">
                            <div className="relative">
                                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" />
                                <input
                                    type="text"
                                    placeholder="Search medications..."
                                    value={searchTerm}
                                    onChange={(e) => setSearchTerm(e.target.value)}
                                    className="pl-10 pr-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                                />
                            </div>
                            <select
                                value={filterStatus}
                                onChange={(e) => setFilterStatus(e.target.value)}
                                className="px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white"
                            >
                                <option value="all">All Status</option>
                                <option value="active">Active</option>
                                <option value="inactive">Inactive</option>
                                <option value="discontinued">Discontinued</option>
                            </select>
                            <select
                                value={sortBy}
                                onChange={(e) => setSortBy(e.target.value)}
                                className="px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white"
                            >
                                <option value="name">Sort by Name</option>
                                <option value="nextDose">Sort by Next Dose</option>
                                <option value="adherence">Sort by Adherence</option>
                                <option value="refill">Sort by Refill Date</option>
                            </select>
                        </div>
                    </div>

                    <div className="space-y-4">
                        {sortedMedications.map((medication, index) => (
                            <motion.div
                                key={medication.id}
                                initial={{ opacity: 0, x: -50 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ delay: index * 0.1 }}
                                className="flex items-center justify-between p-4 bg-slate-700/50 rounded-xl hover:bg-slate-700/70 transition-all"
                            >
                                <div className="flex items-center gap-4">
                                    <div 
                                        className="w-12 h-12 rounded-xl flex items-center justify-center"
                                        style={{ backgroundColor: medication.color }}
                                    >
                                        <Pill className="w-6 h-6 text-white" />
                                    </div>
                                    <div>
                                        <h4 className="font-semibold text-white">{medication.name}</h4>
                                        <p className="text-sm text-slate-400">{medication.dosage} • {medication.frequency}</p>
                                        <div className="flex items-center gap-4 mt-1">
                                            <span className="text-xs text-slate-400">{medication.purpose}</span>
                                            <span className={`text-xs ${getAdherenceColor(medication.adherence)}`}>
                                                {Math.round(medication.adherence * 100)}% adherence
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <div className="flex items-center gap-3">
                                    <div className="text-right">
                                        <p className="text-sm text-slate-400">Supply</p>
                                        <p className="text-sm font-semibold text-white">
                                            {medication.remainingSupply}/{medication.totalSupply}
                                        </p>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-sm text-slate-400">Refill</p>
                                        <p className="text-sm font-semibold text-white">
                                            {new Date(medication.refillDate).toLocaleDateString()}
                                        </p>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <button
                                            onClick={() => setEditingMedication(medication)}
                                            className="p-2 text-slate-400 hover:text-white transition-colors"
                                        >
                                            <Edit2 className="w-4 h-4" />
                                        </button>
                                        <button
                                            onClick={() => deleteMedication(medication.id)}
                                            className="p-2 text-slate-400 hover:text-red-400 transition-colors"
                                        >
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                </motion.div>

                {/* Upcoming Refills */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.3 }}
                    className="bg-slate-800/50 backdrop-blur-lg border border-white/10 rounded-2xl p-6 mt-8"
                >
                    <h3 className="text-lg font-semibold text-white mb-4">Upcoming Refills</h3>
                    <div className="space-y-3">
                        {upcomingRefills.map((refill, index) => (
                            <div key={refill.id} className="flex items-center justify-between p-4 bg-slate-700/50 rounded-xl">
                                <div className="flex items-center gap-4">
                                    <div className="w-10 h-10 bg-gradient-to-r from-orange-500 to-red-500 rounded-lg flex items-center justify-center">
                                        <RefreshCw className="w-5 h-5 text-white" />
                                    </div>
                                    <div>
                                        <h4 className="font-semibold text-white">{refill.medicationName}</h4>
                                        <p className="text-sm text-slate-400">{refill.pharmacy}</p>
                                    </div>
                                </div>
                                <div className="flex items-center gap-3">
                                    <div className="text-right">
                                        <p className="text-sm text-slate-400">Days Until</p>
                                        <p className="text-sm font-semibold text-white">{refill.daysUntil}</p>
                                    </div>
                                    <span className={`px-3 py-1 rounded-full text-xs font-semibold border ${getRefillStatusColor(refill.daysUntil)}`}>
                                        {refill.daysUntil <= 7 ? 'Urgent' : refill.daysUntil <= 14 ? 'Soon' : 'Upcoming'}
                                    </span>
                                    <button className="px-3 py-1 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm">
                                        Order Refill
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                </motion.div>
            </div>

            {/* Add/Edit Medication Modal */}
            <AnimatePresence>
                {(showAddModal || editingMedication) && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 bg-slate-900/95 backdrop-blur-sm z-50 flex items-center justify-center p-4"
                        onClick={() => {
                            setShowAddModal(false);
                            setEditingMedication(null);
                        }}
                    >
                        <motion.div
                            initial={{ scale: 0.9, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            exit={{ scale: 0.9, opacity: 0 }}
                            className="bg-slate-800 rounded-2xl border border-white/10 max-w-2xl w-full max-h-[90vh] overflow-y-auto"
                            onClick={(e) => e.stopPropagation()}
                        >
                            <div className="p-6">
                                <div className="flex items-center justify-between mb-6">
                                    <h3 className="text-xl font-bold text-white">
                                        {editingMedication ? 'Edit Medication' : 'Add New Medication'}
                                    </h3>
                                    <button
                                        onClick={() => {
                                            setShowAddModal(false);
                                            setEditingMedication(null);
                                        }}
                                        className="p-2 text-slate-400 hover:text-white transition-colors"
                                    >
                                        <X className="w-5 h-5" />
                                    </button>
                                </div>

                                <MedicationForm
                                    medication={editingMedication}
                                    onSubmit={editingMedication ? updateMedication : addMedication}
                                    onCancel={() => {
                                        setShowAddModal(false);
                                        setEditingMedication(null);
                                    }}
                                />
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}

// Medication Form Component
function MedicationForm({ medication, onSubmit, onCancel }) {
    const [formData, setFormData] = useState({
        name: medication?.name || '',
        dosage: medication?.dosage || '',
        frequency: medication?.frequency || '',
        times: medication?.times || [],
        startDate: medication?.startDate || '',
        endDate: medication?.endDate || '',
        purpose: medication?.purpose || '',
        instructions: medication?.instructions || '',
        prescribedBy: medication?.prescribedBy || '',
        totalSupply: medication?.totalSupply || '',
        pharmacy: medication?.pharmacy || ''
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        if (medication) {
            onSubmit(medication.id, formData);
        } else {
            onSubmit(formData);
        }
    };

    return (
        <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-2">Medication Name</label>
                    <input
                        type="text"
                        value={formData.name}
                        onChange={(e) => setFormData({...formData, name: e.target.value})}
                        className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                        placeholder="Enter medication name"
                        required
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-2">Dosage</label>
                    <input
                        type="text"
                        value={formData.dosage}
                        onChange={(e) => setFormData({...formData, dosage: e.target.value})}
                        className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                        placeholder="e.g., 500mg"
                        required
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-2">Frequency</label>
                    <select
                        value={formData.frequency}
                        onChange={(e) => setFormData({...formData, frequency: e.target.value})}
                        className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                        required
                    >
                        <option value="">Select frequency</option>
                        <option value="once-daily">Once daily</option>
                        <option value="twice-daily">Twice daily</option>
                        <option value="three-times-daily">Three times daily</option>
                        <option value="four-times-daily">Four times daily</option>
                        <option value="as-needed">As needed</option>
                        <option value="weekly">Weekly</option>
                        <option value="monthly">Monthly</option>
                    </select>
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-2">Purpose</label>
                    <input
                        type="text"
                        value={formData.purpose}
                        onChange={(e) => setFormData({...formData, purpose: e.target.value})}
                        className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                        placeholder="Why are you taking this medication?"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-2">Start Date</label>
                    <input
                        type="date"
                        value={formData.startDate}
                        onChange={(e) => setFormData({...formData, startDate: e.target.value})}
                        className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                        required
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-2">End Date</label>
                    <input
                        type="date"
                        value={formData.endDate}
                        onChange={(e) => setFormData({...formData, endDate: e.target.value})}
                        className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-2">Prescribed By</label>
                    <input
                        type="text"
                        value={formData.prescribedBy}
                        onChange={(e) => setFormData({...formData, prescribedBy: e.target.value})}
                        className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                        placeholder="Doctor's name"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-2">Total Supply</label>
                    <input
                        type="number"
                        value={formData.totalSupply}
                        onChange={(e) => setFormData({...formData, totalSupply: e.target.value})}
                        className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                        placeholder="Number of pills/units"
                    />
                </div>
            </div>
            <div>
                <label className="block text-sm font-medium text-slate-400 mb-2">Instructions</label>
                <textarea
                    value={formData.instructions}
                    onChange={(e) => setFormData({...formData, instructions: e.target.value})}
                    className="w-full px-4 py-2 bg-slate-700/50 border border-white/10 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/30 resize-none"
                    rows={3}
                    placeholder="Special instructions (take with food, avoid alcohol, etc.)"
                />
            </div>
            <div className="flex justify-end gap-3">
                <button
                    type="button"
                    onClick={onCancel}
                    className="px-6 py-2 bg-slate-700 text-white rounded-lg hover:bg-slate-600 transition-colors"
                >
                    Cancel
                </button>
                <button
                    type="submit"
                    className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                >
                    {medication ? 'Update' : 'Add'} Medication
                </button>
            </div>
        </form>
    );
}
